src/api/urls.py
from django.urls import path, include
#from .views import listar_libros, detalle_libro
""" urlpatterns = [
	path('libros/<int:id>',detalle_libro,name = 'detalle_libro'),
	path('libros', listar_libros, name='listar_libros'),
] """

# django rest framework
from .views import LibroViewSet,EmpleadoViewSet,AutorViewSet,SocioViewSet
from rest_framework import routers
app_name = "api"

router = routers.DefaultRouter()
router.register('libro', LibroViewSet)
router.register('empleado', EmpleadoViewSet)
router.register('autor', AutorViewSet)
router.register('socio', SocioViewSet)

urlpatterns = [
		path('',include(router.urls))
]

src/socio/urls.py
from django.urls import path
from .views import (
	EditarSocio,
	CrearSocio,
	ListarSocios,
	activar_socio,
	desactivar_socio
	)

app_name = 'socios'

urlpatterns = [
	path('nuevo/', CrearSocio.as_view(), name= 'CrearSocio'),
	path('listar/', ListarSocios.as_view(), name= 'ListarSocios'),
	path('modificar/<int:pk>/', EditarSocio.as_view(), name='EditarSocio'),
	path('activar/<int:id>/', activar_socio, name= 'activar_socio'),
	path('desactivar/<int:id>/', desactivar_socio, name= 'desactivar_socio'),
]

src/webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import cargar_index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',cargar_index),
    path('home/',cargar_index),
    path('empleados/',include('empleado.urls',namespace='empleados')),
    path('autores/',include('autor.urls',namespace='autores')),
    path('socios/', include('socio.urls',namespace='socios')),
    path('libros/', include('libro.urls',namespace='libros')),
    path('prestamos/',include('biblioteca.urls',namespace='prestamos')),
    path('api/',include('api.urls',namespace='api')),

    #path('api/libros', listar_libros, name='listar_libros'),
]

from django.conf.urls.static import static
from django.conf import settings

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/socio/models.py
from django.db import models
from django.urls import reverse
from .validators import nombreValidator
""" Creacion de la entidad Socio cuenta con:
nombre = nombre del Socio (tipo Str)
apellido = apellido del Socio (tipo Str)
fecha_nacimiento = la fecha de nacimiento del Socio (tipo Date)
activo = si el socio se encuentra activo o no (tipo Bool)
 """
class Socio(models.Model):
    nombre = models.CharField(max_length= 30,validators=[nombreValidator])
    apellido = models.CharField(max_length= 30,validators=[nombreValidator])
    fecha_nacimiento = models.DateField()
    activo = models.BooleanField(default= True)

    def get_absolute_url(self):
        return reverse("socios:EditarSocio", kwargs={"pk": self.pk})
    

    def __str__(self):
        return F"{self.apellido} {self.nombre}"
    
    class Meta:
        ordering = ["apellido", "nombre","fecha_nacimiento"]

src/socio/forms.py
from django.forms import ModelForm
from .models import Socio
from django import forms
from .validators import nombreValidator


class SocioForm(ModelForm):
		nombre  = forms.CharField(min_length=3,max_length=50, validators=[nombreValidator])
		apellido = forms.CharField(min_length=3,max_length=50, validators=[nombreValidator])
		class Meta:
				model = Socio
				fields = ["apellido","nombre","fecha_nacimiento"]
		

src/socio/views.py
from django.shortcuts import redirect,get_object_or_404
from .models import Socio
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from .forms import SocioForm
from django.urls import reverse_lazy
# Create your views here.

class EditarSocio(UpdateView):
    model = Socio
    form_class = SocioForm
    template_name = "socios/editar.html"
    success_url = reverse_lazy('socios:ListarSocios') 

class ListarSocios(ListView):
    model = Socio
    template_name = "socios/listar.html"
    ordering = ("apellido", "nombre")
        
class CrearSocio(CreateView):
    model = Socio
    form_class = SocioForm
    template_name = "socios/crear.html"
    success_url = reverse_lazy('socios:ListarSocios') 

# Create your views here.
def activar_socio(request, id):
    socio = get_object_or_404(Socio, id=id)
    socio.activo = True
    socio.save()

    return redirect(reverse_lazy('socios:ListarSocios'))

def desactivar_socio(request, id):
    socio = get_object_or_404(Socio, id=id)
    socio.activo = False
    socio.save()
    return redirect(reverse_lazy('socios:ListarSocios'))

src/templates/socios/crear.html
{% extends 'base.html' %}
{% block titulo %}Crear Socio{% endblock titulo %}
{% block contenido %}
    <div class="container">
        <div class="text-center">
            <h3 class="title py-3">Crear Socio</h3>
        </div>
        <div class="container border border-primary border-3 rounded bg-primary-subtle p-5 control-ancho">
            <form class="align-center" method="POST" action="">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary" type="submit">Guardar</button>
            </form>
        </div>
        <div class="container text-end pb-3">
            <a class="btn btn-primary my-2" href= {% url 'socios:ListarSocios' %}>Volver al listado</a>
        </div>
    </div>
{% endblock contenido %}

src/templates/socios/editar.html
{% extends 'base.html' %}
{% block titulo %}Editar Socio{% endblock titulo %}
{% block contenido %}
<div class="container">
    <div class="text-center">
        <h3 class="title py-3">Modificar Socio</h3>
    </div>
    <div class="container border border-primary border-3 rounded bg-primary-subtle p-5 control-ancho">
        <form class="align-center" method="POST" action="">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-primary" type="submit">Guardar</button>
        </form>
    </div>
    <div class="container text-end pb-3">
        <a class="btn btn-primary my-2" href= {% url 'socios:ListarSocios' %}>Volver al listado</a>
    </div>
</div>
{% endblock contenido %}

src/templates/socios/listar.html
{% extends 'base.html' %}
{% block titulo %}Listar Socios{% endblock titulo %}
{% block contenido %}
<div class="container">
  <div class="text-center">
    <h3 class="title py-3">Lista de Socios</h3>
  </div>
  <div class="table-responsive-lg">
    <table class="table table-hover align-middle">
      <thead>
        <tr class="bg-primary text-white">
          <th scope="col">APELLIDO</th>
          <th scope="col">NOMBRE</th>
          <th scope="col">FECHA DE NACIMIENTO</th>
          <th scope="col">ESTADO</th>				
          <th scope="col"></th>				
          <th scope="col"></th>				
        </tr>
      </thead>
      <tbody>     
      {% for socio in object_list %}
        {% if socio.activo %}
        <tr class="table-info">
        {% else %}
        <tr class="table-danger">
        {% endif %}
          <td>{{socio.apellido}}</td>
          <td>{{socio.nombre}}</td>
          <td>{{socio.fecha_nacimiento}}</td>
          <td>
            {% if socio.activo %}
            Activo
            {% else %}
            Inactivo
            {% endif %}
          </td>
          <td>
            {% if socio.activo %}
            <a class="btn btn-danger btn-sm" href= {% url 'socios:desactivar_socio' socio.pk %}>Desactivar</a>
            {% else %}
            <a class="btn btn-success btn-sm" href= {% url 'socios:activar_socio' socio.pk %}>Activar</a>
            {% endif %}
          </td>
          <td>
            <a class="btn btn-dark btn-sm" href= {% url 'socios:EditarSocio' socio.pk %}>Editar</a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="container text-end pb-3">
    <a class="btn btn-primary" href= {% url 'socios:CrearSocio' %}>Agregar Socio</a>
  </div>
</div>

{% endblock contenido %}