src/api/urls.py
from django.urls import path, include
#from .views import listar_libros, detalle_libro
""" urlpatterns = [
	path('libros/<int:id>',detalle_libro,name = 'detalle_libro'),
	path('libros', listar_libros, name='listar_libros'),
] """

# django rest framework
from .views import LibroViewSet,EmpleadoViewSet,AutorViewSet,SocioViewSet
from rest_framework import routers
app_name = "api"

router = routers.DefaultRouter()
router.register('libro', LibroViewSet)
router.register('empleado', EmpleadoViewSet)
router.register('autor', AutorViewSet)
router.register('socio', SocioViewSet)

urlpatterns = [
		path('',include(router.urls))
]

src/empleado/urls.py
from django.urls import path
from .views import (
    CrearEmpleado,
    ListarEmpleados,
    EditarEmpleado,
    activar_empleado,
    desactivar_empleado,
)

app_name = 'empleados'

urlpatterns = [
    path('nuevo/',CrearEmpleado.as_view(), name= 'CrearEmpleado' ),
    path('listar/',ListarEmpleados.as_view(), name= 'ListarEmpleados' ),
    path('modificar/<int:pk>/',EditarEmpleado.as_view(), name='EditarEmpleado'),
    path('activar/<int:id>/', activar_empleado, name= 'activar_empleado'),
    path('desactivar/<int:id>/', desactivar_empleado, name= 'desactivar_empleado'),
]

src/webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import cargar_index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',cargar_index),
    path('home/',cargar_index),
    path('empleados/',include('empleado.urls',namespace='empleados')),
    path('autores/',include('autor.urls',namespace='autores')),
    path('socios/', include('socio.urls',namespace='socios')),
    path('libros/', include('libro.urls',namespace='libros')),
    path('prestamos/',include('biblioteca.urls',namespace='prestamos')),
    path('api/',include('api.urls',namespace='api')),

    #path('api/libros', listar_libros, name='listar_libros'),
]

from django.conf.urls.static import static
from django.conf import settings

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/empleado/models.py
from django.db import models
from django.urls import reverse
from .validators import nombreValidator
# Create your models here.

# Modelo para el empleado
class Empleado(models.Model):
    nombre = models.CharField(max_length=30,validators=[nombreValidator])
    apellido = models.CharField(max_length=30,validators=[nombreValidator])
    numero_legajo = models.PositiveIntegerField(unique = True)
    activo = models.BooleanField(default=True)

    class Meta:
        ordering = ["apellido","nombre","numero_legajo"]
    
    def __str__(self):
        return f"{self.nombre},{self.apellido} (legajo n°: {self.numero_legajo})"

    def get_absolute_url(self):
        return reverse("empleados:ListarEmpleados")
    

src/empleado/forms.py
from django import forms
from django.forms import ModelForm
from .models import Empleado
from django import forms
from .validators import nombreValidator
from django import forms
class EmpleadoForm(ModelForm):
	nombre  = forms.CharField(min_length=3,max_length=50, validators=[nombreValidator])
	apellido = forms.CharField(min_length=3,max_length=50, validators=[nombreValidator])
	class Meta:
			model = Empleado
			fields = ["apellido","nombre","numero_legajo"]

src/empleado/views.py
from django.shortcuts import get_object_or_404 , redirect
from .models import Empleado
from .forms import EmpleadoForm
from django.views.generic import UpdateView, ListView,CreateView
from django.urls import reverse_lazy

class EditarEmpleado(UpdateView):
    model = Empleado
    form_class = EmpleadoForm
    template_name = "empleados/editar.html"
    success_url = reverse_lazy("empleados:ListarEmpleados")  

class ListarEmpleados(ListView):
    model = Empleado
    template_name = "empleados/listar.html"
    ordering = ("apellido", "nombre")
        
class CrearEmpleado(CreateView):
    model = Empleado
    form_class = EmpleadoForm
    template_name = "empleados/crear.html"
    success_url = reverse_lazy('empleados:ListarEmpleados') 

# Create your views here.
def activar_empleado(request, id):
    empleado= get_object_or_404(Empleado, id = id)
    empleado.activo = True
    empleado.save()
    
    return redirect(reverse_lazy('empleados:ListarEmpleados'))

def desactivar_empleado(request, id):
    empleado = get_object_or_404(Empleado, id=id)
    empleado.activo = False
    empleado.save()

    return redirect(reverse_lazy('empleados:ListarEmpleados'))

src/templates/empleados/crear.html
{% extends 'base.html' %}
{% block titulo %}Crear Empleado{% endblock titulo %}
{% block contenido %}
    <div class="container">
        <div class="text-center">
            <h3 class="title py-3">Crear Empleado</h3>
        </div>
        <div class="container border border-primary border-3 rounded bg-primary-subtle p-5 control-ancho">
            <form class="align-center" method="POST" action="">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary" type="submit">Guardar</button>
            </form>
        </div>
        <div class="container text-end pb-3">
            <a class="btn btn-primary my-2" href= {% url 'empleados:ListarEmpleados' %}>Volver al listado</a>
        </div>
    </div>
{% endblock contenido %}

src/templates/empleados/editar.html
{% extends 'base.html' %}
{% block titulo %}Editar Empleado{% endblock titulo %}
{% block contenido %}
<div class="container">
    <div class="text-center">
        <h3 class="title py-3">Modificar Empleado</h3>
    </div>
    <div class="container border border-primary border-3 rounded bg-primary-subtle p-5 control-ancho">
        <form class="align-center" method="POST" action="">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-primary" type="submit">Guardar</button>
        </form>
    </div>
    <div class="container text-end pb-3">
        <a class="btn btn-primary my-2" href= {% url 'empleados:ListarEmpleados' %}>Volver al listado</a>
    </div>
</div>
{% endblock contenido %}

src/templates/empleados/listar.html
{% extends 'base.html' %}
{% block titulo %}Listar Empleados{% endblock titulo %}
{% block contenido %}
<div class="container">
  <div class="text-center">
    <h3 class="title py-3">Lista de Empleados</h3>
  </div>
  <div class="table-responsive-lg">
    <table class="table table-hover align-middle">
      <thead>
        <tr class="bg-primary text-white">
          <th scope="col">APELLIDO</th>
          <th scope="col">NOMBRE</th>
          <th scope="col">LEGAJO</th>
          <th scope="col">ESTADO</th>
          <th scope="col"></th>
          <th scope="col"></th>
          {% comment %} podemos agregar la columna detalle
          que al hacer click en una lupa vaya a la url (empleado/pk) {% endcomment %}
        </tr>
      </thead>
      <tbody>
        {% comment %} aqui empleados va a varirar dependiendo 
        de como me pasen las lista desde la views {% endcomment %}
      {% for empleado in object_list %}
        {% if empleado.activo %}
        <tr class="table-info">
        {% else %}
        <tr class="table-danger">
        {% endif %}
          <td>{{empleado.apellido}}</td>
          <td>{{empleado.nombre}}</td>
          <td>{{empleado.numero_legajo}}</td>
          <td>
            {% if empleado.activo %}
            Activo
            {% else %}
            Inactivo
            {% endif %}
          </td>
          <td>
            {% if empleado.activo %}
            <a class="btn btn-danger btn-sm" href= {% url 'empleados:desactivar_empleado' empleado.pk %}>Desactivar</a>
            {% else %}
            <a class="btn btn-success btn-sm" href= {% url 'empleados:activar_empleado' empleado.pk %}>Activar</a>
            {% endif %}
          </td>
          <td>
            <a class="btn btn-dark btn-sm" href= {% url 'empleados:EditarEmpleado' empleado.pk %}>Editar</a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<div class="container text-end pb-3">
  <a class="btn btn-primary" href= {% url 'empleados:CrearEmpleado' %}>Agregar Empleado</a>
</div>
{% endblock contenido %}