src/api/urls.py
from django.urls import path, include
#from .views import listar_libros, detalle_libro
""" urlpatterns = [
	path('libros/<int:id>',detalle_libro,name = 'detalle_libro'),
	path('libros', listar_libros, name='listar_libros'),
] """

# django rest framework
from .views import LibroViewSet,EmpleadoViewSet,AutorViewSet,SocioViewSet
from rest_framework import routers
app_name = "api"

router = routers.DefaultRouter()
router.register('libro', LibroViewSet)
router.register('empleado', EmpleadoViewSet)
router.register('autor', AutorViewSet)
router.register('socio', SocioViewSet)

urlpatterns = [
		path('',include(router.urls))
]

src/autor/urls.py
from django.urls import path
from .views import (
    EditarAutor,
    activar_autor,
    desactivar_autor,
    ListarAutores,
    CrearAutor
    )

app_name = 'autores'

urlpatterns = [
    path('nuevo/',CrearAutor.as_view(), name= 'CrearAutor' ),    
    path('listar/',ListarAutores.as_view(), name='ListarAutores'),
    path('modificar/<int:pk>/',EditarAutor.as_view(), name='EditarAutor'),
    path('activar/<int:id>/',activar_autor, name='activar_autor'),
    path('desactivar/<int:id>/',desactivar_autor, name='desactivar_autor'),
]

src/webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import cargar_index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',cargar_index),
    path('home/',cargar_index),
    path('empleados/',include('empleado.urls',namespace='empleados')),
    path('autores/',include('autor.urls',namespace='autores')),
    path('socios/', include('socio.urls',namespace='socios')),
    path('libros/', include('libro.urls',namespace='libros')),
    path('prestamos/',include('biblioteca.urls',namespace='prestamos')),
    path('api/',include('api.urls',namespace='api')),

    #path('api/libros', listar_libros, name='listar_libros'),
]

from django.conf.urls.static import static
from django.conf import settings

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/templates/autores/crear.html
{% extends 'base.html' %}
{% block titulo %}Crear Autor{% endblock titulo %}
{% block contenido %}
    <div class="container">
        <div class="text-center">
            <h3 class="title py-3">Agregar Autor</h3>
        </div>
        <div class="container border border-primary border-3 rounded bg-primary-subtle p-5 control-ancho">
            <form class="align-center" method="POST" action="">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary" type="submit">Guardar</button>
            </form>
        </div>
        <div class="container text-end pb-3">
            <a class="btn btn-primary my-2" href= {% url 'autores:ListarAutores' %}>Volver al listado</a>
        </div>
    </div>
{% endblock contenido %}

src/templates/autores/editar.html
{% extends 'base.html' %}
{% block titulo %}Editar Autor{% endblock titulo %}
{% block contenido %}
<div class="container">
    <div class="text-center">
        <h3 class="title py-3">Modificar Autor</h3>
    </div>
    <div class="container border border-primary border-3 rounded bg-primary-subtle p-5 control-ancho">
        <form class="align-center" method="POST" action="">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-primary" type="submit">Guardar</button>
        </form>
    </div>
    <div class="container text-end pb-3">
        <a class="btn btn-primary my-2" href= {% url 'autores:ListarAutores' %}>Volver al listado</a>
    </div>
</div>
{% endblock contenido %}

src/templates/autores/listar.html
{% extends 'base.html' %}
{% block titulo %}Listar Autores{% endblock titulo %}
{% block contenido %}
<div class="container">
    <div class="text-center">
        <h3 class="title py-3">Lista de Autores</h3>
    </div>
    <div class="table-responsive-lg">
        <table class="table table-hover align-middle">
            <thead>
                <tr class="bg-primary text-white">
                    <th scope="col">APELLIDO</th>
                    <th scope="col">NOMBRE</th>
                    <th scope="col">NACIONALIDAD</th>
                    <th scope="col">ESTADO</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
            {% for autor in object_list %}
            {% if autor.activo %}
            <tr class="table-info">
            {% else %}
            <tr class="table-danger">
            {% endif %}
                <td>{{autor.apellido}}</td>
                <td>{{autor.nombre}}</td>
                <td>{{autor.nacionalidad}}</td>
                <td>
                {% if autor.activo %}
                Activo
                {% else %}
                Inactivo
                {% endif %}
                </td>
                <td>
                {% if autor.activo %}
                <a class="btn btn-danger btn-sm" href= {% url 'autores:desactivar_autor' autor.pk %}>Desactivar</a>
                {% else %}
                <a class="btn btn-success btn-sm" href= {% url 'autores:activar_autor' autor.pk %}>Activar</a>
                {% endif %}
                </td>
                <td>
                <a class="btn btn-dark btn-sm" href= {% url 'autores:EditarAutor' autor.pk %}>Editar</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="container text-end pb-3">
  <a class="btn btn-primary" href= {% url 'autores:CrearAutor' %}>Agregar Autor</a>
</div>
{% endblock contenido %}