src/api/urls.py
from django.urls import path, include
#from .views import listar_libros, detalle_libro
""" urlpatterns = [
	path('libros/<int:id>',detalle_libro,name = 'detalle_libro'),
	path('libros', listar_libros, name='listar_libros'),
] """

# django rest framework
from .views import LibroViewSet,EmpleadoViewSet,AutorViewSet,SocioViewSet
from rest_framework import routers
app_name = "api"

router = routers.DefaultRouter()
router.register('libro', LibroViewSet)
router.register('empleado', EmpleadoViewSet)
router.register('autor', AutorViewSet)
router.register('socio', SocioViewSet)

urlpatterns = [
		path('',include(router.urls))
]

src/autor/urls.py
from django.urls import path
from .views import (
    EditarAutor,
    activar_autor,
    desactivar_autor,
    ListarAutores,
    CrearAutor
    )

app_name = 'autores'

urlpatterns = [
    path('nuevo/',CrearAutor.as_view(), name= 'CrearAutor' ),    
    path('listar/',ListarAutores.as_view(), name='ListarAutores'),
    path('modificar/<int:pk>/',EditarAutor.as_view(), name='EditarAutor'),
    path('activar/<int:id>/',activar_autor, name='activar_autor'),
    path('desactivar/<int:id>/',desactivar_autor, name='desactivar_autor'),
]

src/empleado/urls.py
from django.urls import path
from .views import (
    CrearEmpleado,
    ListarEmpleados,
    EditarEmpleado,
    activar_empleado,
    desactivar_empleado,
)

app_name = 'empleados'

urlpatterns = [
    path('nuevo/',CrearEmpleado.as_view(), name= 'CrearEmpleado' ),
    path('listar/',ListarEmpleados.as_view(), name= 'ListarEmpleados' ),
    path('modificar/<int:pk>/',EditarEmpleado.as_view(), name='EditarEmpleado'),
    path('activar/<int:id>/', activar_empleado, name= 'activar_empleado'),
    path('desactivar/<int:id>/', desactivar_empleado, name= 'desactivar_empleado'),
]

src/libro/urls.py
from django.urls import path
from .views import (
    CrearLibro,
    EditarLibro,
    ListarLibros,
		desactivar_libro,
    activar_libro,
)

app_name = 'libros'

urlpatterns = [
    path('nuevo/', CrearLibro.as_view(), name= 'CrearLibro' ),
    path('modificar/<int:pk>/',EditarLibro.as_view(), name='EditarLibro'),
    path('listar/',ListarLibros.as_view(), name= 'ListarLibros' ),
    path('activar/<int:id>/', activar_libro, name= 'activar_libro'),
		path('desactivar/<int:id>/', desactivar_libro, name= 'desactivar_libro'),
]

src/socio/urls.py
from django.urls import path
from .views import (
	EditarSocio,
	CrearSocio,
	ListarSocios,
	activar_socio,
	desactivar_socio
	)

app_name = 'socios'

urlpatterns = [
	path('nuevo/', CrearSocio.as_view(), name= 'CrearSocio'),
	path('listar/', ListarSocios.as_view(), name= 'ListarSocios'),
	path('modificar/<int:pk>/', EditarSocio.as_view(), name='EditarSocio'),
	path('activar/<int:id>/', activar_socio, name= 'activar_socio'),
	path('desactivar/<int:id>/', desactivar_socio, name= 'desactivar_socio'),
]

src/webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import cargar_index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',cargar_index),
    path('home/',cargar_index),
    path('empleados/',include('empleado.urls',namespace='empleados')),
    path('autores/',include('autor.urls',namespace='autores')),
    path('socios/', include('socio.urls',namespace='socios')),
    path('libros/', include('libro.urls',namespace='libros')),
    path('prestamos/',include('biblioteca.urls',namespace='prestamos')),
    path('api/',include('api.urls',namespace='api')),

    #path('api/libros', listar_libros, name='listar_libros'),
]

from django.conf.urls.static import static
from django.conf import settings

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/templates/home/home.html
{% extends 'base.html' %}
{% block titulo %}Inicio{% endblock titulo %}
{% load static %}

{% block contenido %}
<div class="container p-5 d-flex bg-primary-subtle text-center">
    <div class="row row-cols-1 row-cols-md-3 g-3 justify-content-center">
        <a class="tarjeta" href="{% url 'empleados:ListarEmpleados' %}">
            <div class="col">
                <div class="card fondo" >
                  <img src="{% static 'imagenes/empleado.jpg' %}" class="card-img-top" style="height:200px" alt="empleados">
                  <div class="card-body">
                    <h5 class="card-title">Empleados</h5>
                  </div>
                </div>
            </div>
        </a>
        <a class="tarjeta" href="{% url 'socios:ListarSocios' %}">
            <div class="col">
                <div class="card fondo">
                  <img src="{% static 'imagenes/socios.jpg' %}" class="card-img-top" style="height:200px" alt="socios">
                  <div class="card-body">
                    <h5 class="card-title">Socios</h5>
                  </div>
                </div>
            </div>
        </a>
        <a class="tarjeta" href="{% url 'autores:ListarAutores' %}">
            <div class="col">
                <div class="card fondo">
                  <img src="{% static 'imagenes/autores.png' %}" class="card-img-top" style="height:200px" alt="autores">
                  <div class="card-body">
                    <h5 class="card-title">Autores</h5>
                  </div>
                </div>
            </div>
        </a>
        <a class="tarjeta" href="{% url 'libros:ListarLibros' %}">
            <div class="col">
                <div class="card fondo">
                    <img src="{% static 'imagenes/libros.jpg' %}" class="card-img-top" style="height:200px" alt="libros">
                    <div class="card-body">
                    <h5 class="card-title">Libros</h5>
                    </div>
                </div>
            </div>
        </a>
        <a class="tarjeta" href="{% url 'prestamos:ListarPrestamosLibro' %}">
            <div class="col">
                <div class="card fondo">
                <img src="{% static 'imagenes/prestamos.jpg' %}" class="card-img-top" style="height:200px" alt="prestamos">
                <div class="card-body">
                    <h5 class="card-title">Prestamos</h5>
                </div>
                </div>
            </div>
        </a>
        
      </div>
</div>
{% endblock contenido %}